In [4]:
import numpy as np

B = np.array([[0.5, 0.2],
              [0.4, -0.1],
              [0.3, 0.4]])
sigma_F = np.array([[0.02, 0.01],
                  [0.01, 0.03]])
Phi = np.diag([0.05, 0.04, 0.03])

In [5]:
sigma = B @ sigma_F @ B.T + Phi

In [6]:
sigma

array([[0.0582, 0.0037, 0.008 ],
       [0.0037, 0.0427, 0.0025],
       [0.008 , 0.0025, 0.039 ]])

In [9]:
Omega = np.diag([0.0025, 0.0025])
v = np.array([0.06, 0.1])
P = np.diag([1, -1])
v = (0.04)

In [15]:
Sigma = np.array([[0.04, 0.01],[0.01, 0.09]])
shrink_factor = 0.3
target = (np.trace(Sigma)/ 2) * np.eye(2)

cov_shrinked = 0.3 * target + 0.7 * Sigma

In [22]:
import numpy as np

# Data
rets = np.array([
    [0.02, 0.01],
    [-0.01, 0.02],
    [0.03, -0.02]
])

# Sample mean
rets_mean = rets.mean(axis=0)

# Centered
centered = rets - rets_mean

# Sample covariance
T = rets.shape[0]
cov_manual = (centered.T @ centered) / (T - 1)

# Result
print("Sample mean:", rets_mean)
print("Sample covariance:\n", cov_manual)


Sample mean: [0.01333333 0.00333333]
Sample covariance:
 [[ 0.00043333 -0.00036667]
 [-0.00036667  0.00043333]]


In [21]:
cov_manual

array([[ 0.00043333, -0.00036667],
       [-0.00036667,  0.00043333]])

In [36]:
import numpy as np

# Correct shapes
B = np.array([[0.05], [0.07]])  # Shape (2,1)
sigma_f = np.array([[0.04]])    # Shape (1,1)
phi = np.diag([0.01, 0.02])     # Shape (2,2)

# Compute
cov = B @ sigma_f @ B.T + phi

In [40]:
x = np.array([[0.1, -0.1], [-0.05, 0.2]])
sigma_0 = np.array([[0.04, 0], [0, 0.09]])
N = 1
w = N / (x.T @ np.linalg.inv(sigma_0) @ x)

In [41]:
w

array([[ 3.6       , -2.76923077],
       [-2.76923077,  1.44      ]])

In [46]:


x = np.array([[0.1, -0.1],
              [-0.05, 0.2]])
sigma_0 = np.array([[0.04, 0],
                    [0, 0.09]])
N_dim = 2  # because x_t is 2-dimensional!

sigma_inv = np.linalg.inv(sigma_0)

# Compute weights per t
w = []

for t in range(x.shape[0]):
    x_t = x[t, :]  # take one row, shape (2,)
    quad_form = x_t @ sigma_inv @ x_t.T  # scalar
    w_t = N_dim / quad_form
    w.append(w_t)

w = np.array(w)
w

array([5.53846154, 3.94520548])

In [47]:

print("Tyler weights:", w)

Tyler weights: [5.53846154 3.94520548]


In [48]:
6/(6.7)

0.8955223880597015

In [57]:
import sympy as sp
pi, Sigma, P, v, Omega, tau, I = sp.symbols('pi, Sigma, P, v, Omega, tau I')

In [79]:
import sympy as sp
n, k = sp.symbols('n, k', positive = True)
pi = sp.MatrixSymbol('pi', n, 1)
Sigma = sp.MatrixSymbol('Sigma', n, n)
P = sp.MatrixSymbol('P', k, n)
Omega = sp.MatrixSymbol('Omega', k, k)
v = sp.MatrixSymbol('v', k, 1)
I = sp.Identity(n)
tau = sp.symbols('tau')


inv_term = ( (tau * Sigma).inv() + P.T * Omega.inv() * P).inv()

middle_term = (  (tau * Sigma).inv() * pi + P.T* Omega.inv() * v)

mu_BL = inv_term * middle_term
mu_BL

(P.T*Omega**(-1)*P + 1/tau*Sigma**(-1))**(-1)*(P.T*Omega**(-1)*v + 1/tau*Sigma**(-1)*pi)

In [67]:
x = np.array([0.05, -0.1, 0.02])
mu = 0
var = 0.04
v = 4
N = 1

for t in range(3):
    x_t = x[t]
    w_t = (v + N)/ (v + (x_t - mu)**2 / var)

In [68]:
w_t

np.float64(1.2468827930174564)

In [84]:
pi = sp.MatrixSymbol('pi', n, 1)   # n x 1 vector
Sigma = sp.MatrixSymbol('Sigma', n, n)  # n x n covariance matrix
P = sp.MatrixSymbol('P', k, n)  # k views on n assets
Omega = sp.MatrixSymbol('Omega', k, k)  # uncertainty of views
v = sp.MatrixSymbol('v', k, 1)  # view vector
I = sp.Identity(n)  # identity matrix
tau = sp.symbols('tau')
