In [1]:
from itertools import accumulate

import numpy as np
import requests
from tensorflow.python.ops.numpy_ops.np_array_ops import newaxis

url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)

<Response [200]>

NameError: name 'con' is not defined

In [7]:
import sqlalchemy as sqla
import pandas as pd
import numpy as np
db = sqla.create_engine('sqlite:///mydata.sqlaite')

pd.read_sql('select * from test', db)

OperationalError: (sqlite3.OperationalError) no such table: test
[SQL: select * from test]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [8]:
np.ones((3, 4, 5), dtype = np.float64).strides

(160, 40, 8)

In [13]:
import numpy as np

ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)

print(np.issubdtype(ints.dtype, np.integer))   # ✅ Note: issubdtype
print(np.issubdtype(floats.dtype, np.floating)) # ✅ Note: issubdtype

np.float64.mro()

True
True


[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [17]:
np.issubdtype(ints.dtype, np.number)

True

In [22]:
arr = np.arange(8)
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [23]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [25]:
other_arr = np.ones((3, 5))

arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
arr = np.arange(15).reshape((5, 3))
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [34]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

np.concatenate([arr1, arr2], axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [35]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [37]:
arr = np.random.randn(5, 2)
arr

array([[ 0.50578773, -2.26935455],
       [ 2.2661557 , -1.08091473],
       [-0.51487741, -1.84908918],
       [ 0.25876419,  0.75233977],
       [-0.3782325 ,  0.7931524 ]])

In [38]:
first, second, third = np.split(arr, [1, 3])
first

array([[ 0.50578773, -2.26935455]])

In [40]:
third

array([[ 0.25876419,  0.75233977],
       [-0.3782325 ,  0.7931524 ]])

In [42]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)

np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.70319185, -0.96231521],
       [-1.31366289,  0.63124673],
       [-0.4366222 , -0.59252589]])

In [44]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [-0.70319185, -0.96231521,  3.        ],
       [-1.31366289,  0.63124673,  4.        ],
       [-0.4366222 , -0.59252589,  5.        ]])

In [47]:
arr = np.arange(3)
arr.repeat(33)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [48]:
arr.repeat([2, 3, 4])


array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [49]:
arr = np.random.randn(2, 2)
arr

array([[-0.64834965, -1.44553158],
       [-0.46795224, -1.34738933]])

In [50]:
arr.repeat(2, axis = 0)

array([[-0.64834965, -1.44553158],
       [-0.64834965, -1.44553158],
       [-0.46795224, -1.34738933],
       [-0.46795224, -1.34738933]])

In [51]:
arr.repeat([2, 3], axis = 0)

array([[-0.64834965, -1.44553158],
       [-0.64834965, -1.44553158],
       [-0.46795224, -1.34738933],
       [-0.46795224, -1.34738933],
       [-0.46795224, -1.34738933]])

In [52]:
arr.repeat([2, 3], axis = 1)

array([[-0.64834965, -0.64834965, -1.44553158, -1.44553158, -1.44553158],
       [-0.46795224, -0.46795224, -1.34738933, -1.34738933, -1.34738933]])

In [56]:
np.tile(arr, 2)

array([[-0.64834965, -1.44553158, -0.64834965, -1.44553158],
       [-0.46795224, -1.34738933, -0.46795224, -1.34738933]])

In [58]:
np.tile(arr, (2, 1))

array([[-0.64834965, -1.44553158],
       [-0.46795224, -1.34738933],
       [-0.64834965, -1.44553158],
       [-0.46795224, -1.34738933]])

In [60]:
np.tile(arr, (3, 2))

array([[-0.64834965, -1.44553158, -0.64834965, -1.44553158],
       [-0.46795224, -1.34738933, -0.46795224, -1.34738933],
       [-0.64834965, -1.44553158, -0.64834965, -1.44553158],
       [-0.46795224, -1.34738933, -0.46795224, -1.34738933],
       [-0.64834965, -1.44553158, -0.64834965, -1.44553158],
       [-0.46795224, -1.34738933, -0.46795224, -1.34738933]])

In [64]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

array([700, 100, 200, 600])

In [67]:
arr.take(inds)

array([700, 100, 200, 600])

In [68]:
arr.put(inds, 32)

In [69]:
arr

array([  0,  32,  32, 300, 400, 500,  32,  32, 800, 900])

In [70]:
inds = [2, 0, 2, 1]
arr = np.random.randn(2, 4)
arr

array([[ 1.33580867e+00,  4.48626907e-01,  4.35021620e-03,
         8.06481215e-01],
       [-1.93606869e+00, -5.30055768e-01, -7.36079532e-01,
         1.46535229e-03]])

In [74]:
arr.take(inds, axis = 1)

array([[ 0.00435022,  1.33580867,  0.00435022,  0.44862691],
       [-0.73607953, -1.93606869, -0.73607953, -0.53005577]])

In [72]:
arr[inds]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [76]:
arr = np.arange(5)
arr * 4

array([ 0,  4,  8, 12, 16])

In [77]:
arr = np.random.randn(4,3)
arr.mean(0)

demeanded = arr - arr.mean(0)

demeanded

array([[ 2.09437298,  0.05897925,  1.28927113],
       [-0.04914491, -1.47041181, -2.36011624],
       [-0.64677864, -0.08474928,  2.14291405],
       [-1.39844943,  1.49618184, -1.07206894]])

In [80]:
a = np.array([1, 2, 3])        # shape (3,)
b = np.array([[10], [20]])     # shape (2, 1)
c = a + b


In [83]:
a + b

array([[11, 12, 13],
       [21, 22, 23]])

In [84]:
arr

array([[ 2.12471147,  0.66941851,  1.16257226],
       [-0.01880643, -0.85997256, -2.48681511],
       [-0.61644015,  0.52568997,  2.01621518],
       [-1.36811095,  2.10662109, -1.19876781]])

In [86]:
row_means = arr.mean(1)
row_means.reshape((4, 1))


array([[ 1.31890074],
       [-1.1218647 ],
       [ 0.64182167],
       [-0.15341922]])

In [89]:
demeaned = arr - row_means.reshape((4, 1))

In [90]:
demeaned.mean(1)

array([ 1.11022302e-16, -7.40148683e-17,  1.48029737e-16,  7.40148683e-17])

In [91]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [92]:
arr - arr.mean(1).reshape((4, 1))

array([[ 0.80581072, -0.64948224, -0.15632849],
       [ 1.10305827,  0.26189214, -1.36495041],
       [-1.25826182, -0.1161317 ,  1.37439351],
       [-1.21469172,  2.26004032, -1.04534859]])

In [93]:
arr.mean(1).reshape((4, 1))

array([[ 1.31890074],
       [-1.1218647 ],
       [ 0.64182167],
       [-0.15341922]])

In [94]:
arr

array([[ 2.12471147,  0.66941851,  1.16257226],
       [-0.01880643, -0.85997256, -2.48681511],
       [-0.61644015,  0.52568997,  2.01621518],
       [-1.36811095,  2.10662109, -1.19876781]])

In [95]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]

arr_3d.shape

(4, 1, 4)

In [97]:
arr_1d = np.random.normal(size = 3)
arr_1d[:, np.newaxis]

array([[ 0.60771945],
       [-0.90700484],
       [ 0.18374606]])

In [98]:
arr_1d[np.newaxis, :]


array([[ 0.60771945, -0.90700484,  0.18374606]])

In [116]:
arr = np.random.randn(3,4, 5)
depth_means = arr.mean(2)
depth_means.shape
demeaned= arr - depth_means[:, :, np.newaxis]

demeaned.mean(2)

array([[-4.44089210e-17,  0.00000000e+00, -2.22044605e-17,
        -4.44089210e-17],
       [-1.11022302e-17, -8.88178420e-17,  6.93889390e-17,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  2.22044605e-17,
         0.00000000e+00]])

In [117]:
def demean_axis(arr, axis = 0):
    means = arr.mean(axis)
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]

In [118]:
arr = np.zeros((4, 3))

In [123]:
col = np.array([1.28, -0.42, 0.44, 1.6])


In [124]:
arr[:] = 5

In [125]:
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [126]:
arr[:2] = [[-1.37], [0.509]]


In [127]:
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [128]:
arr = np.arange(10)
np.add.reduce(arr)


45

In [131]:
np.add.rarr.sum()

AttributeError: 'numpy.ufunc' object has no attribute 'rarr'

In [132]:
np.random.seed(12345)

arr = np.random.randn(5, 5)

arr[::2].sort(1)

In [134]:
arr

array([[-0.5557303 , -0.51943872, -0.20470766,  0.47894334,  1.96578057],
       [ 1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474],
       [-1.29622111,  0.22891288,  0.27499163,  1.00718936,  1.35291684],
       [ 0.88642934, -2.00163731, -0.37184254,  1.66902531, -0.43856974],
       [-1.02122752, -0.5770873 , -0.53974145,  0.47698501,  3.24894392]])

In [135]:
arr[:, :-1] < arr[:, 1:]

array([[ True,  True,  True,  True],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True, False],
       [ True,  True,  True,  True]])

In [137]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis =1)

array([ True, False,  True, False,  True])

In [147]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)


array([ True,  True,  True])

In [138]:
arr = np.arange(15).reshape((3, 5))

np.add.accumulate(arr, axis = 1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [140]:
np.cumsum(arr, axis = 1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [148]:
arr = np.arange(3).repeat([1, 2, 3])

arr

array([0, 1, 1, 2, 2, 2])

In [149]:
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [150]:
x, y = np.random.randn(3, 4), np.random.randn(5)

result = np.subtract.outer(x, y)

result.shape

(3, 4, 5)

In [155]:
print(x.shape); print(y.shape)

(3, 4)
(5,)


In [156]:
arr = np.arange(10)

np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

In [157]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])


array([10, 18, 17])

In [158]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [159]:
np.add.reduceat(arr, [0, 2, 5], axis = 1)

IndexError: index 5 out-of-bounds in add.reduceat [0, 5)

In [ ]:
def add_elements(x, y):
    return x + y

In [160]:
 arr = np.arange(33)

In [167]:
np.accumulate(arr)

AttributeError: module 'numpy' has no attribute 'accumulate'

In [170]:
np.add.at(arr, [2, 3], 3 )

In [173]:
np.add.reduce(arr)

534

In [174]:
np.add.outer(arr, np.arange(3))

array([[ 0,  1,  2],
       [ 1,  2,  3],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10],
       [ 9, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13, 14],
       [13, 14, 15],
       [14, 15, 16],
       [15, 16, 17],
       [16, 17, 18],
       [17, 18, 19],
       [18, 19, 20],
       [19, 20, 21],
       [20, 21, 22],
       [21, 22, 23],
       [22, 23, 24],
       [23, 24, 25],
       [24, 25, 26],
       [25, 26, 27],
       [26, 27, 28],
       [27, 28, 29],
       [28, 29, 30],
       [29, 30, 31],
       [30, 31, 32],
       [31, 32, 33],
       [32, 33, 34]])

In [184]:
arr = np.array([10, 20, 30, 40, 50, 60])
indices = [0, 3, 5]
result = np.add.reduceat(arr, indices)
print(result)

[60 90 60]


In [186]:
def add_elements(x, y):
    return x + y

add_them = np.frompyfunc(add_elements, 2, 1)

add_them(np.arange(8), np.arange(8))


array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [187]:
arr = np.random.randn(10000)

%timeit add_them(arr, arr)

1.19 ms ± 47.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [188]:
%timeit np.add(arr, arr)

3.14 μs ± 662 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [189]:
import numpy as np

arr = np.array([[1, 3, 2],
                [4, 2, 5]])

# Task: Compute cumulative max along each row
result = np.maximum.accumulate(arr, axis=1)
print(result)


[[1 3 3]
 [4 4 5]]


In [193]:
x = np.array([1, 2, 3])
y = np.array([0, 1, 2])

def myfunc(x, y):
    return x**y
myfunc(x, y)

result = np.power.outer(x, y)

result

array([[1, 1, 1],
       [1, 2, 4],
       [1, 3, 9]])

In [195]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])
indices = [0, 2, 5]
result = np.add.reduceat(arr, indices)
result

array([ 30, 120, 130])

In [198]:
dtype = [('x', np.float64), ('y', np.int32)]

sarr = np.array([(1.5, 6), (np.pi, -2)], dtype = dtype)

sarr

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [199]:
sarr[0]

(1.5, 6)

In [200]:
sarr[0]['y']

6

In [201]:
sarr['x']

array([1.5       , 3.14159265])

In [204]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype = dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [205]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]),  'y', np.int32]

In [210]:
data['x']

TypeError: Field elements must be 2- or 3-tuples, got ''y''

In [212]:
arr = np.random.randn(6)
arr.sort()

arr

array([-2.8684566 , -0.97842091, -0.60364122, -0.36927672, -0.04395743,
        1.17812873])

In [214]:
arr = np.random.randn(3, 5)
arr

array([[-0.66000182, -0.33807963,  0.63497703, -0.71606474,  0.0228685 ],
       [-0.13324884, -0.11682442,  0.03503312, -1.79267401, -1.82940241],
       [-0.14848782,  0.04995322, -1.32899112, -0.45067167, -1.02241173]])

In [216]:
arr[:, 0].sort()
arr

array([[-0.66000182, -0.33807963,  0.63497703, -0.71606474,  0.0228685 ],
       [-0.14848782, -0.11682442,  0.03503312, -1.79267401, -1.82940241],
       [-0.13324884,  0.04995322, -1.32899112, -0.45067167, -1.02241173]])

In [218]:
arr = np.random.randn(5)
np.sort(arr)

array([-1.40713387, -0.47359003,  0.19392979,  0.28345813,  0.87670717])

In [219]:
arr

array([ 0.19392979,  0.87670717,  0.28345813, -1.40713387, -0.47359003])

In [222]:
arr = np.random.randn(3, 5)
arr.sort(axis = 1)

In [223]:
arr

array([[-0.93651858, -0.16986601,  0.08360603,  0.10631206,  0.52731415],
       [-1.51974035, -0.5007859 , -0.24616905, -0.04641922,  0.95668424],
       [-0.66749644, -0.28348781, -0.19059901, -0.09342088,  1.14912319]])

In [224]:
arr[:, ::-1]

array([[ 0.52731415,  0.10631206,  0.08360603, -0.16986601, -0.93651858],
       [ 0.95668424, -0.04641922, -0.24616905, -0.5007859 , -1.51974035],
       [ 1.14912319, -0.09342088, -0.19059901, -0.28348781, -0.66749644]])

In [226]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()
indexer

values[indexer]

array([0, 1, 2, 3, 5])

In [227]:
arr = np.random.randn(3, 5)
arr[0] = values

In [228]:
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [-1.79015022,  0.50613633, -1.84093014, -2.06582445, -0.08328621],
       [ 0.61383685, -1.64562276,  1.83888497, -0.13053351, -0.20532461]])

In [231]:
arr[:, arr[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [ 0.50613633, -1.84093014, -0.08328621, -2.06582445, -1.79015022],
       [-1.64562276,  1.83888497, -0.20532461, -0.13053351,  0.61383685]])

In [4]:
import numpy as np
def add_elements(x, y):
    return x + y
add_them = np.frompyfunc(add_elements, 2, 1)

add_them(np.arange(8), np.arange(8))


array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [7]:
add_them = np.vectorize(add_elements, otypes = [np.float64])
add_them(np.arange(8), np.arange(8))
arr = np.random.randn(10000)



In [8]:
%timeit add_them(arr, arr)

1.42 ms ± 45.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])

last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])

sorter = np.lexsort((first_name, last_name))
sorter

array([1, 2, 3, 0, 4])

In [10]:
list(zip(last_name[sorter], first_name[sorter]))


[('Arnold', 'Jane'),
 ('Arnold', 'Steve'),
 ('Jones', 'Bill'),
 ('Jones', 'Bob'),
 ('Walters', 'Barbara')]

In [11]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])

In [13]:
key = np.array([2, 2, 1, 1, 1])

indexer = key.argsort(kind = 'mergesort')
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

In [14]:
np.random.seed(12345)
arr = np.random.randn(20)
arr

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474,
        1.00718936, -1.29622111,  0.27499163,  0.22891288,  1.35291684,
        0.88642934, -2.00163731, -0.37184254,  1.66902531, -0.43856974])

In [15]:
np.partition(arr, 3)

array([-2.00163731, -1.29622111, -0.5557303 , -0.51943872, -0.37184254,
       -0.43856974, -0.20470766,  0.28174615,  0.76902257,  0.47894334,
        1.00718936,  0.09290788,  0.27499163,  0.22891288,  1.35291684,
        0.88642934,  1.39340583,  1.96578057,  1.66902531,  1.24643474])

In [18]:
indices = np.argpartition(arr, 3)
indices

array([16, 11,  3,  2, 17, 19,  0,  7,  8,  1, 10,  6, 12, 13, 14, 15,  5,
        4, 18,  9])

In [19]:
arr.take(indices)

array([-2.00163731, -1.29622111, -0.5557303 , -0.51943872, -0.37184254,
       -0.43856974, -0.20470766,  0.28174615,  0.76902257,  0.47894334,
        1.00718936,  0.09290788,  0.27499163,  0.22891288,  1.35291684,
        0.88642934,  1.39340583,  1.96578057,  1.66902531,  1.24643474])

In [25]:
import numba as nb
@nb.jit
def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count+= 1
    return result / count
x=y = np.random.randn(10000000)
%timeit mean_distance(x, y)

12.4 ms ± 276 μs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [28]:
from numba import vectorize

@vectorize
def nb_add(x, y):
    return x+ y

x = np.arange(10)
nb_add(x, x)

nb_add.accumulate(x, 0)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [30]:
mmap = np.memmap('mymmap', dtype = 'float64', mode = 'w+', shape = (10000, 10000))
mmap

memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [35]:
section = mmap[:5]
section[:] = np.random.randn(5, 10000)

mmap.flush()

In [36]:
mmap

memmap([[ 0.23275331,  1.78686021,  0.97992359, ...,  2.41775622,
         -3.14188089,  0.80611709],
        [ 0.14532681, -0.13024997, -0.84999561, ..., -0.05977103,
          0.48362599, -0.71616606],
        [-0.57893615, -1.56128556,  0.06070886, ..., -0.36330868,
         -0.24724856, -0.22294129],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

In [37]:
del mmap

In [38]:
mmap = np.memmap('mymmap', dtype = 'float64', shape = (10000, 10000))
mmap

memmap([[ 0.23275331,  1.78686021,  0.97992359, ...,  2.41775622,
         -3.14188089,  0.80611709],
        [ 0.14532681, -0.13024997, -0.84999561, ..., -0.05977103,
          0.48362599, -0.71616606],
        [-0.57893615, -1.56128556,  0.06070886, ..., -0.36330868,
         -0.24724856, -0.22294129],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

In [39]:
%xdel mmap

In [40]:
!rm mymmap

In [44]:
arr_c = np.ones((100, 10000), order = 'C')

arr_f = np.ones((100, 10000), order = 'F')

arr_c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [45]:
arr_f.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [46]:
arr_f.flags.f_contiguous

True

In [47]:
%timeit arr_c.sum(1)


398 μs ± 131 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [48]:
%timeit arr_f.sum(1)

454 μs ± 134 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [49]:
arr_f.copy('C').flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [50]:
arr_c[:50].flags.contiguous

True

In [51]:
arr_c[:, :50].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [52]:
'input1'

'input1'

In [64]:
'input2'

'input2'

In [65]:
'input3'

'input3'

In [69]:
foo = 'bar'
foo

'bar'

In [72]:
_69

'bar'

def add_elements(x, y):
    return x + y
add_them = np.frompyfunc(add_elements, 2, 1)
import numpy as np
def add_elements(x, y):
    return x + y
add_them = np.frompyfunc(add_elements, 2, 1)
import numpy as np
def add_elements(x, y):
    return x + y
add_them = np.frompyfunc(add_elements, 2, 1)

add_them
import numpy as np
def add_elements(x, y):
    return x + y
add_them = np.frompyfunc(add_elements, 2, 1)

add_them(np.arange(8), np.arange(8))
add_them = np.vectorize(add_elements, otypes = [np.float64])
add_them(np.arange(8), np.arange(8))
add_them = np.vectorize(add_elements, otypes = [np.float64])
add_them(np.arange(8), np.arange(8))
arr = np.random.randn(10000)

%timeit add_themm(arr, arr)
add_them = np.vectorize(add_elements, otypes = [np.float64])
add_them(np.arange(8), np.arange(8))
arr = np.random.randn(10000)
%timeit add_them(arr, arr)
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])

last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])

so

In [76]:
!cmd

zsh:1: command not found: cmd


In [77]:
output = !cmd args

In [78]:
output

['zsh:1: command not found: cmd']

In [80]:
%alias

Total number of aliases: 12


[('cat', 'cat'),
 ('cp', 'cp'),
 ('ldir', 'ls -F -G -l %l | grep /$'),
 ('lf', 'ls -F -l -G %l | grep ^-'),
 ('lk', 'ls -F -l -G %l | grep ^l'),
 ('ll', 'ls -F -l -G'),
 ('ls', 'ls -F -G'),
 ('lx', 'ls -F -l -G %l | grep ^-..x'),
 ('mkdir', 'mkdir'),
 ('mv', 'mv'),
 ('rm', 'rm'),
 ('rmdir', 'rmdir')]

In [86]:
ip_info = !ifconfig wlan0 | grap "inet "

In [87]:
ip_info

['zsh:1: command not found: grap', 'ifconfig: interface wlan0 does not exist']

In [88]:
foo = 'test*'
!ls $foo

zsh:1: no matches found: test*


In [89]:
%alias ll ls -1

In [90]:
ll /usr

bin
lib
libexec
local
sbin
share
standalone
X11
X11R6


In [91]:
%alias test_alias (cd examples; ls; cd)

In [92]:
test_alias

zsh:cd:1: no such file or directory: examples
mydata.sqlaite Pandas.ipynb


In [103]:
import sys
from IPython.core.debugger import Pdb

# Custom set_trace that drops you into the debugger
def set_trace():
    Pdb().set_trace(sys._getframe().f_back)

# Custom debug wrapper to run a function under the debugger
def debug(func, *args, **kwargs):
    pdb = Pdb()
    return pdb.runcall(func, *args, **kwargs)

def divide(a, b):
    result = a / b
    return result

x = 10
y = 0
print(divide(x, y))




ZeroDivisionError: division by zero

In [108]:
debug(divide, 1, 0)

> /var/folders/32/x9dgly0d26z5yqyvl8t2zw3c0000gn/T/ipykernel_6346/660299463.py(2)divide()
      1 def divide(a, b):
----> 2     result = a / b
      3     return result
      4 
      5 x = 10

1
2
ZeroDivisionError: division by zero
> /var/folders/32/x9dgly0d26z5yqyvl8t2zw3c0000gn/T/ipykernel_6346/660299463.py(2)divide()
      1 def divide(a, b):
----> 2     result = a / b
      3     return result
      4 
      5 x = 10

--Return--
None
> /var/folders/32/x9dgly0d26z5yqyvl8t2zw3c0000gn/T/ipykernel_6346/660299463.py(2)divide()
      1 def divide(a, b):
----> 2     result = a / b
      3     return result
      4 
      5 x = 10



ZeroDivisionError: division by zero

In [ ]:
import time
start = time.time()
for i in range(iterations):
elapsed_per = (time.time() - start) / iterations


In [109]:
strings = ['foo', 'foobar', 'baz', 'qux', 'python', 'Guido Van Rossum'] * 100000

In [110]:
method1 = [x for x in strings if x.startswith('foo')]
method2 = [x for x in strings if x[:3] == 'foo']



In [111]:
%time metod1 = [x for x in strings if x.startswith('foo')]


CPU times: user 83.3 ms, sys: 2.9 ms, total: 86.2 ms
Wall time: 84.5 ms


In [112]:
%time method2 = [x for x in strings if x[:3] == 'foo']

CPU times: user 66.5 ms, sys: 2.72 ms, total: 69.3 ms
Wall time: 67.9 ms
